# Generated by Django 2.2.19 on 2022-11-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221102_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Укажите название ингридиента', max_length=200, verbose_name='Название ингридиента'),
        ),
    ]
