# Generated by Django 2.2.19 on 2022-11-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221110_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagInRecipe',
        ),
    ]
