# Generated by Django 2.2.19 on 2022-11-07 15:43

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221103_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Выберите тег', image_field=None, max_length=7, samples=(('#FF0000', 'Завтрак'), ('#0000FF', 'Обед'), ('#008000', 'Ужин'), ('#7FFFD4', 'Суп'), ('#FFA500', 'Десерт'), ('#90EE90', 'Салат'), ('#EE82EE', 'Соус'), ('#8B4513', 'Напиток')), verbose_name='hex цвета тэга'),
        ),
    ]
